package com.ritesh.parser.core.bank

import com.ritesh.parser.core.TransactionType
import com.ritesh.parser.core.test.ExpectedTransaction
import com.ritesh.parser.core.test.ParserTestCase
import com.ritesh.parser.core.test.SimpleTestCase
import com.ritesh.parser.core.test.ParserTestUtils
import org.junit.jupiter.api.TestFactory
import java.math.BigDecimal

class AdditionalParserFactoryTest {
    @TestFactory fun registeredParsers() = ParserTestUtils.runFactoryTestSuite(listOf(
        SimpleTestCase(bankName = ApolloParser().getBankName(), sender = "apollo", currency = "ETB", message = "Your account 1*00 was credited with ETB 100.00 by Example Shop. Available Balance: ETB 900.00.", expected = ExpectedTransaction(amount = BigDecimal("100.00"), currency = "ETB", type = TransactionType.INCOME), shouldHandle = true),
        SimpleTestCase(bankName = AwashBankParser().getBankName(), sender = "AWASH BANK", currency = "ETB", message = "ETB 100.00 has been credited to your account from Example Shop on: 01-01-2026. Balance is ETB 900.00.", expected = ExpectedTransaction(amount = BigDecimal("100.00"), currency = "ETB", type = TransactionType.INCOME), shouldHandle = true),
        SimpleTestCase(bankName = BSFBankParser().getBankName(), sender = "BSF", currency = "SAR", message = "عملية حوالة مالية صادرة مقبولة\nخصمت من حساب ****1000\nإلى Example Shop\nالقيمة SAR 100.00\nالرسوم SAR 1.00", expected = ExpectedTransaction(amount = BigDecimal("100.00"), currency = "SAR", type = TransactionType.EXPENSE), shouldHandle = true),
        SimpleTestCase(bankName = BancoAgricolaParser().getBankName(), sender = "AGRICOLA", currency = "USD", message = "Compra por USD100.00 en Example Shop el 01/01/2026.", expected = ExpectedTransaction(amount = BigDecimal("100.00"), currency = "USD", type = TransactionType.EXPENSE), shouldHandle = true),
        SimpleTestCase(bankName = BancoCuscatlanParser().getBankName(), sender = "BCUSCATLAN", currency = "USD", message = "Compra CUSCATLAN 1000 por USD100.00 en Example Shop el 01/01/2026.", expected = ExpectedTransaction(amount = BigDecimal("100.00"), currency = "USD", type = TransactionType.EXPENSE), shouldHandle = true),
        SimpleTestCase(bankName = BancoPromericaParser().getBankName(), sender = "PROMERICA", currency = "USD", message = "Consumo TTA *1000 por USD100.00 en Example Shop el 01/01/2026.", expected = ExpectedTransaction(amount = BigDecimal("100.00"), currency = "USD", type = TransactionType.EXPENSE), shouldHandle = true),
        SimpleTestCase(bankName = BankOfAbyssiniaParser().getBankName(), sender = "BOA", currency = "ETB", message = "Your account ****1000 was debited with ETB 100.00. Available Balance: ETB 900.00.", expected = ExpectedTransaction(amount = BigDecimal("100.00"), currency = "ETB", type = TransactionType.EXPENSE), shouldHandle = true),
        SimpleTestCase(bankName = BkashParser().getBankName(), sender = "bKash", currency = "BDT", message = "Payment of Tk 100.00 is successful. Balance Tk 900.00. TrxID 000000000001", expected = ExpectedTransaction(amount = BigDecimal("100.00"), currency = "BDT", type = TransactionType.EXPENSE), shouldHandle = true),
        SimpleTestCase(bankName = ChaseUKParser().getBankName(), sender = "ChaseUK", currency = "GBP", message = "£100.00 just landed in Example Account from Example Shop", expected = ExpectedTransaction(amount = BigDecimal("100.00"), currency = "GBP", type = TransactionType.INCOME), shouldHandle = true),
        SimpleTestCase(bankName = CitizensBankParser().getBankName(), sender = "CTZN_ALERT", currency = "NPR", message = "Your account ####1000 is debited NPR 100.00. Remarks: Example Shop Av Bal: 900.00", expected = ExpectedTransaction(amount = BigDecimal("100.00"), currency = "NPR", type = TransactionType.EXPENSE), shouldHandle = true),
        SimpleTestCase(bankName = D360BankParser().getBankName(), sender = "D360Bank", currency = "SAR", message = "International Online Purchase\nCard: *1000 - VISA\nAmount: TRY 200.00 (SAR 100.00)\nAt: Example Shop", expected = ExpectedTransaction(amount = BigDecimal("100.00"), currency = "SAR", type = TransactionType.EXPENSE), shouldHandle = true),
        SimpleTestCase(bankName = GTBankParser().getBankName(), sender = "GTBank", currency = "NGN", message = "Acct: ****1000\nAmt: NGN100.00 DR\nDesc: Example Shop\nBal: NGN900.00", expected = ExpectedTransaction(amount = BigDecimal("100.00"), currency = "NGN", type = TransactionType.EXPENSE), shouldHandle = true),
        SimpleTestCase(bankName = JanaSmallFinanceBankParser().getBankName(), sender = "JM-JANABK-S", currency = "INR", message = "Your acct XX1000 is credited with INR 100.00 on 01-Jan-26 from Example Shop. UPI Ref no 000000000001. JANA SFB", expected = ExpectedTransaction(amount = BigDecimal("100.00"), currency = "INR", type = TransactionType.INCOME), shouldHandle = true),
        SimpleTestCase(bankName = LumbiniBikashBankParser().getBankName(), sender = "LBBL_SMART", currency = "NPR", message = "NPR 100.00 withdrawn from A/C ####1000. Remarks: Example Shop;", expected = ExpectedTransaction(amount = BigDecimal("100.00"), currency = "NPR", type = TransactionType.EXPENSE), shouldHandle = true),
        SimpleTestCase(bankName = MachchhapuchreBankParser().getBankName(), sender = "MBL_ALERT", currency = "NPR", message = "NPR 100.00 withdrawn from account ####1000. Remarks: Example Shop Available Bal: 900.00", expected = ExpectedTransaction(amount = BigDecimal("100.00"), currency = "NPR", type = TransactionType.EXPENSE), shouldHandle = true),
        SimpleTestCase(bankName = MoniepointParser().getBankName(), sender = "Moniepoint", currency = "NGN", message = "Debit Alert\nAcc: ****1000\nAmt: NGN100.00\nDesc: Example Shop\nBal: NGN900.00", expected = ExpectedTransaction(amount = BigDecimal("100.00"), currency = "NGN", type = TransactionType.EXPENSE), shouldHandle = true),
        SimpleTestCase(bankName = NDBBankParser().getBankName(), sender = "NDB ALERT", currency = "LKR", message = "LKR 100.00 debited from AC XXXXXXXX1000 as POS TXN at Example Shop. Avl Bal 900.00", expected = ExpectedTransaction(amount = BigDecimal("100.00"), currency = "LKR", type = TransactionType.EXPENSE), shouldHandle = true),
        SimpleTestCase(bankName = NationalBankOfEgyptParser().getBankName(), sender = "BanK-AlAhly", currency = "EGP", message = "تم إضافة تحويل لحظي لحسابكم رقم 1000 بمبلغ 100.00 جم من Example Shop رقم مرجعي 000000000001", expected = ExpectedTransaction(amount = BigDecimal("100.00"), currency = "EGP", type = TransactionType.INCOME), shouldHandle = true),
        SimpleTestCase(bankName = NationalSavingsBankParser().getBankName(), sender = "NSB", currency = "LKR", message = "LKR 100.00 Debited from your A/c XXXXXXXX1000 on 01/01/2026 at 12:00. AvlBal LKR 900.00. @ Example Shop. ATM POS Transaction.", expected = ExpectedTransaction(amount = BigDecimal("100.00"), currency = "LKR", type = TransactionType.EXPENSE), shouldHandle = true),
        SimpleTestCase(bankName = NationsTrustBankParser().getBankName(), sender = "NationsSMS", currency = "LKR", message = "Transaction for LKR 100.00 approved on your Card 0****1000 at Example Shop Available Bal LKR 900.00", expected = ExpectedTransaction(amount = BigDecimal("100.00"), currency = "LKR", type = TransactionType.CREDIT), shouldHandle = true),
        SimpleTestCase(bankName = NepalBankParser().getBankName(), sender = "NBL_ALERT", currency = "NPR", message = "Your account ####1000 debited NPR 100.00 on 01-01-2026.", expected = ExpectedTransaction(amount = BigDecimal("100.00"), currency = "NPR", type = TransactionType.EXPENSE), shouldHandle = true),
        SimpleTestCase(bankName = NepalSBIBankParser().getBankName(), sender = "NSBI_ALERT", currency = "NPR", message = "Account XX1000 debited by NPR 100.00. Ref: Example Shop.", expected = ExpectedTransaction(amount = BigDecimal("100.00"), currency = "NPR", type = TransactionType.EXPENSE), shouldHandle = true),
        SimpleTestCase(bankName = PasargadBankParser().getBankName(), sender = "WEPOD", currency = "IRR", message = "000.1000 -100 01/01_12:00 مانده: 900", expected = ExpectedTransaction(amount = BigDecimal("100"), currency = "IRR", type = TransactionType.EXPENSE), shouldHandle = true),
        SimpleTestCase(bankName = PluxeeBankParser().getBankName(), sender = "PLUXEE", currency = "INR", message = "Rs.100.00 spent on card no. XX1000 at Example Shop. Avl bal Rs.900.00", expected = ExpectedTransaction(amount = BigDecimal("100.00"), currency = "INR", type = TransactionType.EXPENSE), shouldHandle = true),
        SimpleTestCase(bankName = SiketBankParser().getBankName(), sender = "SIKET BANK", currency = "ETB", message = "Your Account ****1000 Credited with ETB 100.00. Current Balance is ETB 900.00. Reference number 000000000001", expected = ExpectedTransaction(amount = BigDecimal("100.00"), currency = "ETB", type = TransactionType.INCOME), shouldHandle = true),
        SimpleTestCase(bankName = StandardCharteredNepalParser().getBankName(), sender = "SC_ALERT", currency = "NPR", message = "NPR 100.00 debited from your account 00001000 on 01-01-2026.", expected = ExpectedTransaction(amount = BigDecimal("100.00"), currency = "NPR", type = TransactionType.EXPENSE), shouldHandle = true),
        SimpleTestCase(bankName = StandardCharteredNigeriaParser().getBankName(), sender = "SCBANK", currency = "NGN", message = "Debit Alert! Acct: xxxxxx1000, Amt: NGN100.00, Desc: Example Shop, Date: 01-Jan-2026, Bal: NGN900.00", expected = ExpectedTransaction(amount = BigDecimal("100.00"), currency = "NGN", type = TransactionType.EXPENSE), shouldHandle = true),
        SimpleTestCase(bankName = Trading212Parser().getBankName(), sender = "Trading212", currency = "GBP", message = "You earned £100.00 interest on uninvested cash!", expected = ExpectedTransaction(amount = BigDecimal("100.00"), currency = "GBP", type = TransactionType.INCOME), shouldHandle = true),
        SimpleTestCase(bankName = VFDBankParser().getBankName(), sender = "VFD", currency = "NGN", message = "Acct: xxx1000\nAmt: N100.00 DR\nChgs: N1.00\nDesc: Example Shop\nBalance:N900.00", expected = ExpectedTransaction(amount = BigDecimal("100.00"), currency = "NGN", type = TransactionType.EXPENSE), shouldHandle = true),
        SimpleTestCase(bankName = ZamZamBankParser().getBankName(), sender = "ZAMZAM BANK", currency = "ETB", message = "Your account ****1000 has been credited by Example Shop with ETB 100.00. Your current balance is ETB 900.00.", expected = ExpectedTransaction(amount = BigDecimal("100.00"), currency = "ETB", type = TransactionType.INCOME), shouldHandle = true)
    ), "Additional bank registrations")
}
